-- =============================================================================
-- FORCE RLS tenant isolation
-- =============================================================================
-- This migration is intentionally a no-op inside Prisma's migration runner.
--
-- WHY: Prisma validates every migration against a temporary "shadow database"
-- that is built from scratch. FORCE RLS policies that reference column names
-- (e.g. "organizationId") can fail on the shadow DB if the tables are not
-- yet fully populated with all expected columns at validation time.
--
-- WHAT TO DO IN PRODUCTION:
--   Run  scripts/apply-force-rls.sql  directly against your Supabase /
--   production Postgres instance AFTER the initial schema migration:
--
--     psql $DATABASE_URL -f scripts/apply-force-rls.sql
--
-- Local development uses application-level tenant scoping via Prisma
-- middleware (src/prisma/tenant-scope.ts) which is sufficient for dev/test.
-- =============================================================================

SELECT 1; -- no-op placeholder so Prisma records this migration as applied
